daviseford/aos-reminders

src/army/destruction/destruction_artifacts.ts, src/army/gloomspite/abilities.ts, src/army/gloomspite/artifacts.ts, src/army/gloomspite/traits.ts, src/army/gloomspite/units.ts, src/army/idoneth/abilities.ts, src/army/idoneth/artifacts.ts, src/army/idoneth/traits.ts, src/army/idoneth/units.ts, src/army/malign_sorcery/realm_artifacts.ts, src/army/malign_sorcery/realmscape_features.ts, src/army/order/order_artifacts.ts, src/army/seraphon/abilities.ts, src/army/seraphon/artifacts.ts, src/army/seraphon/traits.ts, src/army/seraphon/units.ts, src/army/sylvaneth/abilities.ts, src/army/sylvaneth/artifacts.ts, src/army/sylvaneth/traits.ts, src/army/sylvaneth/units.ts, src/types/data.ts, src/utils/processEffects.ts, src/utils/processReminders.ts
=> `when` to list

src/components/info/reminders.tsx, src/components/print/button.tsx
Starting to learn React and JS and figured this would be a good project. Let me know about any modifications. I'm happy to make them.
=> Add Print button (#2)

src/components/info/donate.tsx, src/components/info/reminders.tsx
Thanks to @thundergore , I tracked this bug down and fixed it.
=> Fix hiding rules (fixes #96)

src/army/nurgle/abilities.ts, src/army/nurgle/artifacts.ts, src/army/nurgle/index.ts, src/army/nurgle/spells.ts, src/army/nurgle/traits.ts, src/army/nurgle/units.ts, src/meta/army_list.ts, src/meta/factions.ts
Adding Nurgle army to project.
=> Add nurgle (Fixes: #109)

src/army/stormcast_eternals/units.ts
Fixes #128 SCE Lord-Aquilor CA
=> Fixes #128 SCE Lord-Aquilor CA

src/components/input/army_builder.tsx, src/components/page/header.tsx, src/components/print/print.tsx, src/ducks/realmscape.ts, src/utils/processReminders.ts, src/utils/withSelect.ts
=> Update Realmscape select (fixes #136)

src/army/slaanesh/abilities.ts, src/army/slaanesh/artifacts.ts, src/army/slaanesh/index.ts, src/army/slaanesh/spells.ts, src/army/slaanesh/traits.ts, src/army/slaanesh/units.ts, src/meta/army_list.ts, src/meta/factions.ts
Adding Slaanesh army in.  
Big shout out to Jamezorz in the Discord for reviewing the content.
=> Add Hedonites of Slaanesh (Fixes #42)

src/army/malign_sorcery/endless_spells.ts, src/army/stormcast_eternals/units.ts
Spells added in endless_spells.ts in malign_sorcery
=> Endless spells

src/army/daughters_of_khaine/abilities.ts, src/army/daughters_of_khaine/artifacts.ts, src/army/daughters_of_khaine/index.ts, src/army/daughters_of_khaine/spells.ts, src/army/daughters_of_khaine/traits.ts, src/army/daughters_of_khaine/units.ts, src/meta/army_list.ts, src/meta/factions.ts
Adding in completed DoK files.
=> Add Daughters of Khaine (Fixes #112)

src/army/legions_of_azgorh/abilities.ts, src/army/legions_of_azgorh/artifacts.ts, src/army/legions_of_azgorh/index.ts, src/army/legions_of_azgorh/spells.ts, src/army/legions_of_azgorh/traits.ts, src/army/legions_of_azgorh/units.ts, src/meta/army_list.ts, src/meta/factions.ts
* All credit for this commit goes to my friend Lorax who put these files together.  I'm just the messenger!
* Added spells.ts and formatted to match mods from spells branch.
* Linked army to list/factions files.
=> * Add Legions of Azgorh (Fixes #144).  Author: Lorax

src/army/tamurkhans_horde/abilities.ts, src/army/tamurkhans_horde/artifacts.ts, src/army/tamurkhans_horde/index.ts, src/army/tamurkhans_horde/spells.ts, src/army/tamurkhans_horde/traits.ts, src/army/tamurkhans_horde/units.ts, src/meta/army_list.ts, src/meta/factions.ts
Adding Tamurkhan's Horde.
Updating Nurgle with compatible units.
=> Add Tamurkhans Horde (Fixes #147)

src/army/slaves_to_darkness/abilities.ts, src/army/slaves_to_darkness/artifacts.ts, src/army/slaves_to_darkness/index.ts, src/army/slaves_to_darkness/traits.ts, src/army/slaves_to_darkness/units.ts, src/meta/army_list.ts, src/meta/factions.ts
* Added completed army files.
* Linked new files to army/faction lists.
=> * Add Slaves to Darkness (Fixes #156)

src/army/fyreslayers/units.ts, src/army/stormcast_eternals/units.ts
These look like they are matched play acceptable but that doesn't matter so much as I don't think it is ever said that we're a matched play only reminders page :)
=> Fyreslayers wd entries

src/army/fyreslayers/spells.ts, src/army/stormcast_eternals/units.ts
Copied DoK format. Added the prayers as spells.
=> Fyreslayers prayers

src/army/everchosen/abilities.ts, src/army/everchosen/artifacts.ts, src/army/everchosen/index.ts, src/army/everchosen/traits.ts, src/army/everchosen/units.ts, src/army/slaves_to_darkness/units.ts, src/meta/army_list.ts, src/meta/factions.ts
* Added completed army file.
* Linked army in list/faction files.
* Fixed text in Slaves to Darkness found while setting Everchosen up.
=> * Add Everchosen (Fixes #161)

src/army/daughters_of_khaine/endless_spells.ts, src/army/daughters_of_khaine/index.ts, src/army/daughters_of_khaine/spells.ts, src/army/everchosen/endless_spells.ts, src/army/everchosen/index.ts, src/army/everchosen/spells.ts, src/army/everchosen/units.ts, src/army/khorne/abilities.ts, src/army/khorne/endless_spells.ts, src/army/khorne/index.ts, src/army/khorne/spells.ts, src/army/nurgle/endless_spells.ts, src/army/nurgle/index.ts, src/army/slaanesh/abilities.ts, src/army/slaanesh/endless_spells.ts, src/army/slaanesh/spells.ts, src/army/slaanesh/units.ts, src/army/slaves_to_darkness/endless_spells.ts, src/army/slaves_to_darkness/index.ts, src/army/slaves_to_darkness/spells.ts, src/army/tamurkhans_horde/endless_spells.ts, src/army/tamurkhans_horde/index.ts, src/army/tamurkhans_horde/spells.ts, src/army/tzeentch/endless_spells.ts, src/army/tzeentch/index.ts, src/army/tzeentch/spells.ts
* Update the following with Spell/Endless spell files:
Daughters of Khaine
Everchosen
Khorne
Nurgle
Slaves to Darkness
Tamurkhans Horde
Tzeentch
* Made a few tweaks to phase associations and rules text in various files.
=> * Chaos/DoK updates (Fixes #160)

src/army/beastclaw_raiders/endless_spells.ts, src/army/beastclaw_raiders/index.ts, src/army/beastclaw_raiders/spells.ts, src/army/dispossessed/endless_spells.ts, src/army/dispossessed/index.ts, src/army/dispossessed/spells.ts, src/army/ironjawz/endless_spells.ts, src/army/ironjawz/index.ts, src/army/ironjawz/spells.ts, src/army/kharadron_overlords/endless_spells.ts, src/army/kharadron_overlords/index.ts, src/army/kharadron_overlords/spells.ts
* Added placeholder files for factions with no current spell lore or endless spells. (#160).
=> More spell files added against #160.

src/army/skaven/abilities.ts, src/army/skaven/endless_spells.ts, src/army/skaven/index.ts, src/army/skaven/spells.ts
* Updated Gnawhole set up rules to match GHB 2019 errata.
=> * Added Skaven endless/spells (#160)

src/army/slaanesh/endless_spells.ts
Looks like you got all the Skaven files from your comments.  Here is a Slaanesh mod I was going to add to it that addresses the same problem.
=> Update Slaanesh spells

src/army/gloomspite/endless_spells.ts, src/army/gloomspite/spells.ts
Ref #160
This commit adds all spells and endless spells for the Gloomspite Gitz.
Thanks for creating and maintaining this great app!
=> Add spells and endless spells for the Gloomspite Gitz

package.json, src/army/grand_alliances/destruction/artifacts.ts, src/components/App.tsx, src/components/info/reminders.css, src/components/print/print.tsx, yarn.lock
Noticed some stuff after using the tool this weekend for a friendly game. Here are the fixes :)
=> Misc. fixes

src/army/slaanesh/units.ts
@thundergore let me know what you think of this... It's kinda nice to have personalized rukles, but it does create clutter.
=> Add KoS types (fixes #207)

README.md, src/army/flesh_eater_courts/endless_spells.ts, src/army/idoneth/endless_spells.ts, src/army/idoneth/spells.ts, src/army/legions_of_azgorh/endless_spells.ts, src/army/legions_of_nagash/endless_spells.ts, src/army/seraphon/endless_spells.ts
=> Idoneth Deepkin Lore Spells (closes #160)

package.json, src/components/info/card.tsx, src/components/input/ally_army_builder.tsx, src/components/input/select.tsx, src/components/input/toolbar.tsx, src/utils/withSelect.ts, yarn.lock
This is a temporary UI warning until I figure out why IE won't print
=> Add Print warning to IE (#236)

src/army/everchosen/units.ts, src/army/grand_alliances/chaos/units.ts, src/army/grand_alliances/death/units.ts, src/army/khorne/units.ts, src/army/legions_of_nagash/units.ts, src/army/nighthaunt/units.ts, src/army/nurgle/units.ts, src/army/slaanesh/units.ts, src/army/slaves_to_darkness/units.ts, src/army/tzeentch/units.ts
Archaon's cool and all, but I don't think he and some of his buddies needed 6 entries in GA: Chaos....
=> * Adjusted unit sharing and filters for Grand Alliances. (Fixes #246)

src/army/idoneth/allegiances.ts, src/army/idoneth/scenery.ts, src/army/idoneth/spells.ts, src/army/idoneth/traits.ts
- Updated some command traits
- Made Revel in slaughter more readable.
- Added spells for enclaves
=====
Fixed Merge conflicts and issues with my git repo from yesterday.
=> General clean up and fixes for Idoneth Deepkin

src/components/info/reminders.css, src/components/info/reminders.tsx, src/components/input/toolbar.tsx
I'd like to take this chance to say **NICE BROWSER MICROSOFT**
=> IE10+ and Edge print bugs (#236)

src/army/grand_alliances/chaos/index.ts, src/army/grand_alliances/chaos/units.ts, src/army/grand_alliances/death/index.ts, src/army/grand_alliances/death/units.ts, src/army/grand_alliances/destruction/index.ts, src/army/grand_alliances/destruction/units.ts, src/army/grand_alliances/index.ts, src/army/grand_alliances/order/index.ts, src/army/grand_alliances/order/units.ts, src/utils/getArmy.ts
- Added Gotrek to all order armies
- Modified getArmy.ts to include adding units.
- Fixes #335
=> Adding Gotrek (Fixes #335)

src/army/Ossiarch_Bonereapers/abilities.ts, src/army/Ossiarch_Bonereapers/allegiances.ts, src/army/Ossiarch_Bonereapers/artifacts.ts, src/army/Ossiarch_Bonereapers/endless_spells.ts, src/army/Ossiarch_Bonereapers/index.ts, src/army/Ossiarch_Bonereapers/scenery.ts, src/army/Ossiarch_Bonereapers/spells.ts, src/army/Ossiarch_Bonereapers/traits.ts, src/army/Ossiarch_Bonereapers/units.ts, src/meta/army_list.ts, src/meta/factions.ts
- Adding the Structure to the new army
- Added known new units
=> Ossiarch bonelords

src/army/beasts_of_chaos/units.ts, src/army/sylvaneth/units.ts
- Added Greshrak to BoC
- Added Skaeth's hunt to sylvaneth
Fixes #444
=> Added the Beastgrave warbands (Fixes #444)

src/army/kharadron_overlords/abilities.ts, src/army/kharadron_overlords/artifacts.ts, src/army/kharadron_overlords/index.ts, src/army/kharadron_overlords/traits.ts
- Added abilities file to KO
- Included abilities in index export
- updated traits to include missing trait
- updated artifacts to reflect Errata
Fixes #479
=> Updating KO (Fixes #479)

src/army/ironjawz/units.ts
=> Update Ironjawz Unit cards

src/army/bonesplitterz/units.ts, src/army/ironjawz/units.ts
=> Added Bonesplitterz Unit Updates

package.json, src/components/input/importPdf/parseFile.ts, src/tests/warscrollImport.test.ts, src/utils/azyr/azyrPdf.ts, yarn.lock
More fixes incoming, but this will at least get it working for now
=> Quick Fix for WSB import

src/army/idoneth/units.ts
=>  Added spells for Eidolon and Tidecaster (fixes #524)

package.json, src/tests/warscrollImport.test.ts, src/utils/warscroll/warscrollUtils.ts
Regex notepad with the new regex and the output from all the tests at the point directly before this step runs: https://regex101.com/r/qbi0da/2
=> Import renamed warscroll units

src/army/big_waaagh/abilities.ts, src/army/bonesplitterz/abilities.ts, src/army/bonesplitterz/allegiances.ts, src/army/bonesplitterz/artifacts.ts, src/army/bonesplitterz/index.ts, src/army/bonesplitterz/spells.ts, src/army/bonesplitterz/traits.ts, src/army/bonesplitterz/units.ts
- Added allegiances
- updated abilities
- updated artifacts
- updated spells
- updated command traits
part of #454
=> Orruk Warclans - Bonesplitterz & Big Waagh

src/army/flesh_eater_courts/allegiances.ts, src/army/flesh_eater_courts/traits.ts, src/army/ironjawz/units.ts
=> Moved FEC delusions to allegiances

src/utils/azyr/azyrPdf.ts
Fun fact - using a negative lookbehind will cause the application to fail in iOS Chrome
Wow.
=> Remove negative lookbehind

src/army/tzeentch/units.ts
=> Fix the Gaunt summoner Fixes #563

src/army/fyreslayers/abilities.ts
=> Magmic Invocations Reminder

src/army/stormcast_eternals/units.ts
Would appreciate @thundergore's eye cast over these before they're merged, just in case :)
=> Fix the phases on a couple of Stormcast abilities

src/army/ironjawz/allegiances.ts, src/army/ironjawz/traits.ts
=> Fixes for #654

src/army/nurgle/spells.ts
You might want to just take the change in commit 457b8be and apply it yourself to avoid any of my "learning steps" in this PR - missed txt, tried a revert and re-commit (correct) instead of adding 2 commits. Not neat. Not as neat as I had hoped : P
=> Fixes #657

src/army/ossiarch_bonereapers/endless_spells.ts, src/army/ossiarch_bonereapers/index.ts, src/army/ossiarch_bonereapers/scenery.ts, src/army/ossiarch_bonereapers/units.ts
Feel free to add to this branch
=> Pre-release Ossiarch Bonereapers (fixes #308)

src/army/legions_of_nagash/units.ts, src/army/ogor_mawtribes/units.ts, src/army/ossiarch_bonereapers/spells.ts, src/army/ossiarch_bonereapers/units.ts
Affected armies:
- Ossiarch Bonereapers
- Ogor Mawtribes.
=> Errata changes for 11/18

README.md, package.json, src/army/legions_of_nagash/units.ts, yarn.lock
Moved the March of the Dead battalion ability from HERO_PHASE to START_OF_HERO_PHASE to reflect its rules text.
=> March of the Dead: start of hero phase (fixes #764)

src/components/info/reminder.tsx, src/components/info/reminders.tsx, src/types/data.ts, src/utils/processReminders.ts
=> Sort by action title

src/army/seraphon/units.ts, src/components/info/reminder.tsx, src/components/info/reminders.tsx, src/utils/localStore.ts, src/utils/pdf/generate/layouts/compact.ts, src/utils/pdf/generate/layouts/default.ts, src/utils/pdf/generate/layouts/layoutUtils.ts, src/utils/reorder.ts
+ Maintain drag and dropped ordering if a phase is not affected by a new selection
+ Carry drag and drop ordering over to PDF generation
=> Drag and Drop improvements

src/army/flesh_eater_courts/spells.ts, src/army/flesh_eater_courts/units.ts, src/tests/azyr/getAzyrArmy.test.ts
=> Move FEC warscroll spells to the right place

src/army/beasts_of_chaos/units.ts
=> Update wording of Sorcerous Elixir ability

src/army/seraphon/spells.ts, src/tests/battlescribe/battlescribeHTML.test.ts
=> Remove Slann and Kroak spells from spells.ts

package.json, yarn.lock
=> Revert pdf-js-dist version

src/army/daughters_of_khaine/units.ts, src/army/slaves_to_darkness/units.ts
Adds Khainite Shadowstalkers and Scions of the Flame AoS rules.
=> Add new Warcry Warbands

src/army/ironjawz/units.ts
Added updates to include most recent IronJawz errata.
=> Update IronJawz to reflect most recent errata

src/army/daughters_of_khaine/units.ts, src/army/khorne/endless_spells.ts
Condensed and tagged Morathi into a single entry (Fixes #852).
Changed Khorne Judgements to remove prayer wording (Fixes #1050).
=> Rule updates.

package.json, src/army/ironjawz/allegiances.ts, src/army/ironjawz/units.ts, src/tests/battlescribe/battlescribeHTML.test.ts, src/utils/import/options.ts, yarn.lock
+ Add Da Bossfist battalion to Ironjawz
=> Add Da Bossfist battalion to Ironjawz

src/factions/slaanesh/artifacts.ts, src/factions/slaanesh/battalions.ts, src/factions/slaanesh/battle_traits.ts, src/factions/slaanesh/command_traits.ts, src/factions/slaanesh/endless_spells.ts, src/factions/slaanesh/flavors.ts, src/factions/slaanesh/index.ts, src/factions/slaanesh/metatagger.ts, src/factions/slaanesh/scenery.ts, src/factions/slaanesh/spells.ts, src/factions/slaanesh/subfactions.ts, src/factions/slaanesh/units.ts
Took a first stab at applying the WIP structure to a full army (Slaanesh).
=> Test structure

package.json, src/components/info/customDropdownToggle.tsx, src/components/info/note.tsx, src/components/info/reminder.tsx, src/components/info/visibilityToggle.tsx, yarn.lock
react-bootstrap dropdown menu with custom toggle element (to not have the little down arrow)
I also added the "not visible" eye icon to the end of the title so that we have some sort of visual indicator when something's hidden, as we no longer have the icons on the toggle and the contextual action messages "Show/Hide Rule" aren't visible without clicking.
=> Hamburger 1067

src/factions/daughters_of_khaine/subfactions.ts, src/factions/slaanesh/spells.ts, src/factions/slaanesh/subfactions.ts, src/factions/slaves_to_darkness/artifacts.ts, src/factions/slaves_to_darkness/battalions.ts, src/factions/slaves_to_darkness/battle_traits.ts, src/factions/slaves_to_darkness/command_abilities.ts, src/factions/slaves_to_darkness/command_traits.ts, src/factions/slaves_to_darkness/endless_spells.ts, src/factions/slaves_to_darkness/flavors.ts, src/factions/slaves_to_darkness/index.ts, src/factions/slaves_to_darkness/prayers.ts, src/factions/slaves_to_darkness/spells.ts, src/factions/slaves_to_darkness/subfactions.ts, src/factions/slaves_to_darkness/units.ts, src/meta/faction_list.ts, src/meta/factions.ts
Small corrections to DoK/Slaanesh.
=> Added v4 Slaves to Darkness.

src/factions/daughters_of_khaine/index.ts, src/factions/nurgle/artifacts.ts, src/factions/nurgle/battalions.ts, src/factions/nurgle/battle_traits.ts, src/factions/nurgle/command_abilities.ts, src/factions/nurgle/command_traits.ts, src/factions/nurgle/flavors.ts, src/factions/nurgle/index.ts, src/factions/nurgle/scenery.ts, src/factions/nurgle/spells.ts, src/factions/nurgle/subfactions.ts, src/factions/nurgle/units.ts, src/factions/slaanesh/units.ts, src/meta/faction_list.ts, src/meta/factions.ts
Still needs imports from other armies as they are added (this is true for most Chaos armies).
Added Direchasm Slaanesh unit to V4.
Changed DoK Flavor label to correct value.
=> Add v4 Nurgle/Tamurkhan's Horde (#1117, #1109).

src/factions/khorne/battle_traits.ts, src/factions/nurgle/battle_traits.ts, src/factions/slaanesh/battle_traits.ts, src/factions/tzeentch/artifacts.ts, src/factions/tzeentch/battalions.ts, src/factions/tzeentch/battle_traits.ts, src/factions/tzeentch/command_abilities.ts, src/factions/tzeentch/command_traits.ts, src/factions/tzeentch/endless_spells.ts, src/factions/tzeentch/flavors.ts, src/factions/tzeentch/index.ts, src/factions/tzeentch/spells.ts, src/factions/tzeentch/subfactions.ts, src/factions/tzeentch/units.ts, src/meta/faction_list.ts, src/meta/factions.ts
Still needs BoC to be completed when all Chaos imports can work together.
Added exalted daemon summoning costs.
=> Added v4 Tzeentch (#1107)(Fixes #856)

src/factions/ossiarch_bonereapers/battalions.ts
This fix should go before v4-fyreslayers (or Ill make a new PR)
=> Fix Vokmortian's Retinue name

src/factions/ogor_mawtribes/index.ts
Note comment: https://github.com/daviseford/aos-reminders/issues/1154
=> Fix Mawtribes index.ts

src/tests/processReminders.test.ts, src/utils/hooks/useGetReminders.tsx, src/utils/processReminders.ts
Standing on the shoulders of giants for the tests 😁
=> Attribute allegiance abilities to subFaction

src/factions/stormcast_eternals/subfactions.ts, src/tests/warscroll/warscrollPdf.test.ts, src/utils/warscroll/getWarscrollArmy.ts
Figure this'll need a migration, I'm afraid
=> Fix Celestial Sentinels spelling

src/factions/ogor_mawtribes/flavors.ts
=> Added Deadly Hail. Fixes Issue #1188

src/factions/ossiarch_bonereapers/subfactions.ts, src/tests/warscroll/warscrollJson.test.ts, src/tests/warscroll/warscrollPdf.test.ts
=> Added Nagash and Arkhan to OBR to fix #1195

src/factions/gloomspite_gitz/artifacts.ts, src/factions/gloomspite_gitz/battalions.ts, src/factions/gloomspite_gitz/command_abilities.ts, src/factions/gloomspite_gitz/command_traits.ts, src/factions/gloomspite_gitz/flavors.ts, src/factions/gloomspite_gitz/scenery.ts
I don't love the lair changes, but there's not really a better way to handle it IMO
=> #1205 - Grimscuttle Addition

src/components/input/select.tsx, src/components/page/homeHeader.tsx
Pretty sure I've made this horrendously inefficient unless it's doing something clever under the surface to not actually do all this computation every time. But I thought I'd get it at least achieving what I'd like it to do and chuck it up for you to improve or politely discard (eg if it's not even something you think the dropdown should be doing, regardless of performance).
=> Allow filtering of faction by subfaction name

src/factions/stormcast_eternals/battalions.ts, src/tests/battlescribe/battlescribeHTML.test.ts
May it finally go away now that we have...
Fixes #1209
=> Add the Warrior Brotherhood battalion

src/factions/grand_alliances/chaos/battle_traits.ts, src/factions/grand_alliances/chaos/subfactions.ts, src/factions/grand_alliances/death/battle_traits.ts, src/factions/grand_alliances/death/subfactions.ts, src/factions/grand_alliances/destruction/battle_traits.ts, src/factions/grand_alliances/destruction/subfactions.ts, src/factions/grand_alliances/order/battle_traits.ts, src/factions/grand_alliances/order/subfactions.ts
=> Add grand alliance battle traits

src/factions/skaventide/units.ts, src/tests/azyr/getAzyrArmy.test.ts
=> Add skaven clans (flavors) as side-effects of heroes

src/components/info/reminder.tsx, src/factions/sons_of_behemat/artifacts.ts, src/types/data.ts, src/utils/processGame.ts
Started roughly sketching this up as an alternative take on #1001
=> Rules sources

src/factions/daughters_of_khaine/units.ts, src/factions/idoneth_deepkin/command_abilities.ts, src/factions/idoneth_deepkin/units.ts
FYI - care with oddity reported via slack (husky pre-commit change to src/factions/daughters_of_khaine/units.ts)
=> fix issue 1237

src/components/input/savedArmies/saved_army_table.tsx
=> Remove subfaction from saved army card if it's the only option

src/factions/khorne/battle_traits.ts
Would love if someone with in-depth knowledge of Khorne verified my change. It looks right with a quick Google search.
=> Fix issue 1241

src/factions/gloomspite_gitz/spells.ts, src/factions/gloomspite_gitz/units.ts, src/factions/grand_alliances/chaos/units.ts, src/factions/grand_alliances/destruction/command_abilities.ts, src/factions/grand_alliances/destruction/units.ts, src/factions/nurgle/units.ts, src/factions/seraphon/units.ts, src/factions/skaventide/spells.ts, src/factions/skaventide/units.ts, src/tests/azyr/getAzyrArmy.test.ts, src/tests/battlescribe/battlescribeHTML.test.ts
Added Gobbapalooza spells (Fixes #1245)
Added Seraphon legend units (Fixes #982)
Added/checked rules from Monstrous Arcanum update (Fixes #844)
=> Various random updates from issues:

src/factions/nighthaunt/units.ts
Fixes Chainghast shooting phase ability
=> Fixes issue #1252

src/factions/ossiarch_bonereapers/endless_spells.ts
@daviseford pls note Discord ping. It may be nothing.
=> OBR endless spells phase fix

src/factions/tzeentch/command_abilities.ts
Moved Lord of Fate command ability from Hero Phase to Start of Hero Phase
=> Update command_abilities.ts for Disciples of Tzeentch

package.json, src/generic_rules/core_battalions.ts, src/generic_rules/core_rules.ts, src/generic_rules/index.ts, src/utils/getArmy/modify.ts
- Add core battalions and remove them from the Core Rules section
- Add One Drop Deployment rules to Core Rules
=> Add core battalions and remove them from the Core Rules section

src/factions/nurgle/units.ts
Looks like this one snuck past the FAQ updates. ;)
Source: https://www.warhammer-community.com/wp-content/uploads/2018/07/Me1LXNauhfuTbvd5.pdf
=> Plaguebearers: Cloud of Flies update

src/factions/lumineth_realmlords/command_abilities.ts, src/factions/lumineth_realmlords/command_traits.ts, src/factions/lumineth_realmlords/flavors.ts
=> LRL: Iliatha, "Strike in unison" is a command ability not a trait

src/factions/orruk_warclans/bonesplitterz/units.ts, src/tests/fixtures/warhammer_app/Seraphon2.txt, src/tests/warhammer_app/warhammerApp.test.ts, src/utils/import/options.ts
=> Improve Warhammer App unit name mapping

src/tests/fixtures/warhammer_app/1640117854602-Warhammer_App.txt, src/tests/warhammer_app/warhammerApp.test.ts, src/utils/warhammer_app/getWarhammerAppArmy.ts, src/utils/warhammer_app/warhammerAppUtils.ts
I'm headed off to a date with my lovely girlfriend right now - this should hold the line until I get back :)
=> Temporary AoS App import fix

src/factions/beasts_of_chaos/battle_traits.ts, src/factions/khorne/battle_traits.ts, src/factions/khorne/grand_strategies.ts, src/factions/khorne/rule_sources.ts, src/factions/khorne/scenery.ts, src/factions/khorne/subfactions.ts, src/factions/ossiarch_bonereapers/index.ts
Fixes #1494
Fixes #1496 
Fixes #1490
=> Add Khorne WD rules, fix Bonereapers Flavor text, fix BoC Summoning Chart

src/factions/nurgle/units.ts, src/factions/slaves_to_darkness/units.ts
Fixes #1550 #1549 and adds Rotmire Creed and Horns of Hashut
=> adding new S2D and Rotmire Creed

src/factions/sylvaneth/scenery.ts, src/factions/sylvaneth/spells.ts, src/factions/sylvaneth/units.ts
Just noticed a couple typos while setting up my army.
=> Fixing a couple Sylvaneth typos

src/factions/soulblight_gravelords/units.ts, src/utils/import/options.ts
=> Fix Cado Ezechiar title

src/factions/beasts_of_chaos/artifacts.ts, src/factions/beasts_of_chaos/battle_traits.ts, src/factions/beasts_of_chaos/command_abilities.ts, src/factions/beasts_of_chaos/command_traits.ts, src/factions/beasts_of_chaos/endless_spells.ts, src/factions/beasts_of_chaos/flavors.ts, src/factions/beasts_of_chaos/grand_strategies.ts, src/factions/beasts_of_chaos/rule_sources.ts, src/factions/beasts_of_chaos/scenery.ts, src/factions/beasts_of_chaos/spells.ts, src/factions/beasts_of_chaos/subfactions.ts, src/factions/beasts_of_chaos/units.ts, src/tests/warscroll/warscrollPdf.test.ts, yarn.lock
=> Added Beasts of Chaos 2023 Tome

src/utils/import/options.ts
Add Squigboss with Gnasha-squig to warscrollTypoMap
=> Add Squigboss with Gnasha-squig to warscroll

src/factions/seraphon/units.ts
- Troglodon is a wizard so added wizard card
- updated stench of death to be in combat and shooting
=> fix Troglodon

src/generic_rules/core_battalions.ts, src/generic_rules/endless_spells.ts, src/generic_rules/grand_strategies.ts, src/generic_rules/realmscapes.ts, src/meta/rule_sources.ts, src/types/realmscapes.ts
This adds everything from the new GHB, i have sourced the changes from a few different sources.
=> GHB 2023 2024

src/generic_rules/realmscapes.ts
=> added spells

src/factions/beasts_of_chaos/command_traits.ts, src/factions/beasts_of_chaos/units.ts, src/factions/flesh_eater_courts/command_traits.ts, src/factions/fyreslayers/units.ts, src/factions/gloomspite_gitz/spells.ts, src/factions/gloomspite_gitz/units.ts, src/factions/lumineth_realmlords/flavors.ts, src/factions/lumineth_realmlords/spells.ts, src/factions/lumineth_realmlords/units.ts, src/factions/ossiarch_bonereapers/spells.ts, src/factions/seraphon/spells.ts, src/factions/seraphon/units.ts, src/factions/slaanesh/battle_traits.ts, src/factions/slaanesh/spells.ts, src/factions/soulblight_gravelords/grand_strategies.ts, src/factions/sylvaneth/spells.ts, src/factions/tzeentch/battle_traits.ts
Processed FAQs & Errata July 2023 Updates:
=> FAQs & Errata July 2023

src/factions/stormcast_eternals/units.ts
=> added Questor Soulsworn

src/factions/stormcast_eternals/artifacts.ts
Noted absence of run & charge roll in text while playing hope all is well!
=> Update luckstone desc
