daviseford/aos-reminders

.gitignore
src/components/info/reminders.css
src/components/info/reminders.tsx

Per #40 , added `page-break-inside` properties to each phase to prevent breaking cards across pages.

Add PageBreak to each phase (fixes #40)

---

src/army/dispossessed/abilities.ts
src/army/dispossessed/artifacts.ts
src/army/dispossessed/index.ts
src/army/dispossessed/traits.ts
src/army/dispossessed/units.ts
src/meta/army_list.ts
src/meta/factions.ts

Adds everyone's favourite battletome-less beardos!
The imports at the top of the files seemed to not point to the correct folders,  for example, in `abilities.ts` it was:
```
import { HERO_PHASE } from 'types/phases'
```
When to me, it should be
```
import { HERO_PHASE } from '../../types/phases'
```
But maybe I didn't set it up correctly on my end. If that's the case let me know and I'll fix that.
- I didn't add veteran abilities like "can attack 2 times instead of 1" or "can take X, Y, or Z weapons". It seemed like those were omitted in the other armies.
- If this PR is fine I wouldn't mind doing Kharadron Overlords next

Dispossessed

---

src/army/stormcast_eternals/units.ts

- The shield ability for the Stardrake is missing
- Gavriel Surehearts command ability is showing the old wording
- Ordinator hit buff works in combat phase, also

SC fixes #124

---

README.md
src/components/App.test.tsx
src/tests/__mock.ts
src/tests/utils.test.ts
src/types/army.ts
src/utils/processReminders.ts

+ When two units share a similar effect name, their entry is combined.
(cherry picked from commit 53cd40e49d3c969c0b51a0312db22e71bf6230c0)
+ This commit introduced bugs. This branch fixes them.
+ I also added tests for the bug.

Fixing merged entries (fixes #183) (#182)

---

package.json
src/components/info/reminders.tsx
src/components/input/toolbar.tsx
yarn.lock

I've just added a warning to Firefox users. They make up 6% of the app's users, so I don't want to leave them stranded long-term, but doing this warning is quicker than any other solution I can think of.
Firefox users will see a warning sign on the "Print Page" button. If they hover over it, they will see the following pop-up:

Add Print Warning for Firefox users (also fixes #131)

---

src/army/stormcast_eternals/endless_spells.ts

I find that the second-half of Burning Vengeance is easily missed. With that in mind, it might be helpful to split the description into multiple phases. Also, clean up the text to reflect what happens in each phase.

Added start of round  phase for Everblaze Comet

---

README.md
clean.js
src/army/beasts_of_chaos/abilities.ts
src/army/beasts_of_chaos/allegiances.ts
src/army/beasts_of_chaos/artifacts.ts
src/army/beasts_of_chaos/endless_spells.ts
src/army/beasts_of_chaos/index.ts
src/army/beasts_of_chaos/spells.ts
src/army/beasts_of_chaos/traits.ts
src/army/beasts_of_chaos/units.ts
src/meta/army_list.ts
src/meta/factions.ts

Added army/beasts_of_chaos, with abilities, allegiances, artifacts, endless_spells, index, spells, traits and units based in the Beasts of Chaos Battletome.
Also included the BoC in the meta/army_list and meta/factions.
The missing things are all the 'when' fields in all army/beasts_of_chaos/*.ts
If missing something something besides that, notify me.

Add Beasts of Chaos (fixes #197)

---

README.md
src/army/legions_of_azgorh/units.ts

LoA daemonsmiths weren't marked as wizards and were missing the Ash Storm spell

Added in missing magic & spell details for Legion of Azgorh Daemonsmiths

---

src/army/stormcast_eternals/abilities.ts

There's no mention in the Shock and Awe ability that it only applies to Scions of the Storm

Fix wording for Shock and Awe allegiance ability

---

src/army/slaanesh/spells.ts

On a casting roll of 10+ it heals D6 instead of D3

Fixed progeny of damnation

---

src/army/stormcast_eternals/units.ts

The full wording of the rule has "at the start of the combat phase"; it is identical to the rule on the Knight-Incantor.

Fix the timing of Spirit Flasks on Lord-Arcanums

---

src/components/input/select.tsx

My first thought was to try to make it so you could hold Ctrl or Cmd to select multiple at a time, but while looking at how it might be implemented I found this built-in option and I like the behaviour so PRing it to see what you think of it.

Set SelectMulti inputs to stay open after selections

---

src/army/stormcast_eternals/units.ts

Store anniversary model. Doesn't have points, so not in warscroll builder. Also not in the app (including the non-Azyr reference bit). But there's a warscroll in the box, so she's usable in Open and Narrative.
https://www.tga.community/forums/topic/18313-aos-2-stormcast-eternals-discussion/?do=findComment&comment=371824
Uncertain about whether the second half of The Malleus Occulum should have the "If your battle is taking place in Ulgu..." bit. On the one hand, it's entirely redundant as that's the only time that spell will be in play. On the other hand, the player might not know off-hand what Mystifying Miasma is or when it would be in play, so keeping the condition in there helps them ignore it when not in Ulgu.

Add Knight-Questor Larissa Shadowstalker

---

src/army/nurgle/units.ts
src/army/slaves_to_darkness/units.ts

- Added skaven pestilens units to nurgle
- Added chaos sorcerer lord to list of slaves units to be exported to chaos gods
Fixes #452

Skaven Pestilens into Nurgle (fixes #452)

---

src/army/generic/scenery.ts

I don't think this scenery piece is in either Azyr or warscrollbuilder, so there shouldn't be any import issues I don't think.

Fix typo in Sigmarite Dais

---

src/army/tzeentch/units.ts

The effects now procs on unmodified 6s, not on 6+ (huge nerf)

Update Tzaangor Skyfires' Judgement from Afar

---

src/components/print/pdfModal.tsx

Only seemed to happen when the filename isn't changed in the modal
When clicking `Download`, the `_reminders` suffix would again be
appended, so the filename seen in the native save dialog was of the
form Faction_Reminders_Reminders.pdf

Stop appending _reminders to default pdf filename a second time

---

src/components/info/notification_banner.tsx
src/components/routes/Home.tsx
src/utils/localStore.ts

+ Adds a re-usable banner that can be hidden and saves its hidden state in localStorage so it doesn't pop up after it's been dismissed
+ Adds a banner telling users that Orruk/CoS are coming!

Add a Notification Banner for CoS/Orruks

---

src/army/beasts_of_chaos/units.ts
src/army/tzeentch/units.ts

Reported by Capt. Raccoon in the discord. 
- The BoC abilities were correct while the Tzeentch ones were outdated.  Changed it so we only have Tzaangors (and tzaangor friends) from one location to keep it consistent. Will make it easier to update in the future as well.

Switched Tzaangors to pull from BoC

---

src/army/ironjawz/traits.ts
src/army/legion_of_blood/traits.ts
src/army/legions_of_nagash/traits.ts

Should address the following two from #517 
`failedImport-Warscroll Builder-Mighty Waaagh!`
`failedImport-Warscroll Builder-Swift Strikes`

Fix trait typos for imports

---

src/army/ironjawz/units.ts
src/tests/warscroll/warscrollPdf.test.ts
src/utils/import/options.ts

Our data matched wsb but not Azyr.
The Azyr typo map was the wrong way around, so wasn't doing any good.
This updates us to use the spelling from the book, which is what Azyr has.
Therefore the mapping that was backwards for Azyr is now the correct one for wsb 😅 
**Updates a live unit name so will need migrating**

Change canonical spelling of Gore-gruntas and redo mappings

---

src/army/ironjawz/units.ts

The Destructive Bulk ability on the generic Megaboss on Maw-krusha
doesn't have one of the paragraphs from Gordrakk's Massively Destructive
Bulk ability

Remove Gordrakk-specific para from Maw-krusha ability

---

package.json
src/army/cities_of_sigmar/units.ts

Fixes #621 
Added in the extended rosters for Cities
- SCE 
- Sylvaneth for use in living cities
- KO for use in tempest eye

Added extended rosters to cities

---

src/army/fyreslayers/traits.ts
src/army/ironjawz/traits.ts
src/army/ogor_mawtribes/traits.ts
src/army/stormcast_eternals/traits.ts
src/tests/azyr/getAzyrArmy.test.ts
src/tests/warscroll/warscrollPdf.test.ts
src/types/data.ts
src/utils/import/options.ts
src/utils/textUtils.ts

Marks all traits that had `(Mount)` in the name, and removes that
Other traits will need identifying and tagging
This change was kinda guesswork, but it seemed to work...

Mark mount traits and display them as such in the reminder

---

src/army/kharadron_overlords/units.ts

Clarified warscroll abilities and corrected inaccurate ability descriptions. I mostly just edited descriptions but I changed the phase of disembark on line 98. I also changed the Vessel/Overburdened abilities since the Ironclad and Frigate abilities have the same name but different numbers. (lines 81-85, 324-328, 360-364). I also added the Skyhook ability the ironclad should have on line 365.

Updated Kharadron Overlords warscroll abilities (fixes #756)

---

package.json
src/army/gloomspite/shared.ts
src/army/gloomspite/traits.ts
src/army/gloomspite/units.ts
src/components/input/army_builder_cards.ts
src/ducks/selections.ts
src/tests/azyr/getAzyrArmy.test.ts
src/tests/battlescribe/battlescribeHTML.test.ts
src/tests/warscroll/warscrollPdf.test.ts
src/types/data.ts
src/utils/analytics.ts
src/utils/getArmy/getCollection.ts
src/utils/import/addSideEffectsToImport.ts
src/utils/import/index.ts
src/utils/import/removeSideEffectsFromImport.ts
src/utils/import/selectionLookup.ts
src/utils/mapTwoListsToDict.ts
yarn.lock

Fixes #579, and resolves the remaining failing test from #582 
Approach is:
- when constructing army collection, when an `Entry` is created from an `Effect`, store this in a variable on it
- after importing all selections from a pdf, and before adding side effects, remove _all_ side effects (as indicated by the above flag)
Notes:
- addresses the Storm Lance behaviour and tests
- identifies an erroneous Battlescribe case, with a unit with the wrong CA, so changes the test to not expect that to work
- causes a reordering of selections in some cases, so those tests have been trivially updated
- logs to Google Analytics in case this is helpful

Import ignore side effect selections

---

src/army/bonesplitterz/units.ts
src/army/ironjawz/units.ts

Updating the bonesplitterz and ironjawz units to match the book/warscrolls

Warclans rules update (fixes #759)

---

src/components/info/card.tsx
src/css/index.scss
src/tests/battlescribe/battlescribeHTML.test.ts

Got the following messages the other day.
> this link doesn't restore fully on mobile for me BTW
> The same for anyone else?
> I only get the unit selection
> Oops, just me, I'm an idiot
Obviously, all but the units card were collapsed, but it really wasn't clear that the shared link had worked properly. This is also true with importing and loading.
So I decided to work up a solution showing the number of selected items on hidden cards.
Considered doing it only on mobile but figured it might be useful across the board. One-line change if not.
Could super do with a review, not least as I tried lots of things and I'm not sure I've removed everything extraneous: there could easily be unused props bouncing around in there. Also my code is likely to be incredibly unidiomatic, cos I'm just not …

Show selection counts on collapsed cards

---

package.json
src/components/App.tsx
src/components/info/banners/update_banner.tsx
src/components/input/savedArmies/save_army_btn.tsx
src/components/input/shareArmy/share_army_btn.tsx
src/components/input/toolbar/clear_army_btn.tsx
src/components/input/toolbar/toolbar.tsx
src/components/page/homeHeader.tsx
src/components/page/navbar.tsx
src/components/payment/giftSubscriptions.tsx
src/components/payment/pricingPlans.tsx
src/components/routes/Redeem.tsx
src/context/useSavedArmies.tsx
src/index.tsx
src/utils/loadArmy/loadArmyHelpers.ts
src/utils/localStore.ts
yarn.lock

There's a very real extent to which
But this seems to work and I've not found any issues with the persistence. It does make the Favorite Faction feature a lot less relevant. The Clear Army button very much came out of no longer being able to just refresh the page to clear it, and switching back and forth between factions is a faff (and not even obvious to everyone as a way of achieving that)
I think I've caught everything I need to in the reset button.
Very happy for UI improvements to be made and any technical stuff that needs doing too!

Redux persist and a Clear Army button

---

src/army/skaven/endless_spells.ts

It was changed from 26" to 13" in an errata

Fix Warp Lightning Vortex range

---

src/army/stormcast_eternals/abilities.ts

It's only for the same *turn* that the unit was set up. I can't think of any cases where a Stormcast unit could set up during an enemy turn, nor an enemy shoot during the Stormcast turn, so I think it's only relevant in the combat phase.
Also fixes some typos of 'set up'

Remove 'Shock and Awe' from shooting phase

---

src/army/tzeentch/abilities.ts
src/army/tzeentch/allegiances.ts
src/army/tzeentch/units.ts

- Changed gaunt summoner to start of hero phase
- Changed Destiny dice to include can't be rerolled or modified
- Fixed typo in Guild of Summoners.
fixes #848

Typo fixes (fixes #848)

---

src/army/legion_of_chaos_ascendant/index.ts
src/army/tzeentch/index.ts

These can easily be shortened but the full names seemed to still fit when I had a quick play with the browser size

Add missing allegiance types

---

src/army/nurgle/units.ts

"Charge roll of 1" doesn't make sense, since they're 2d6.  Original rule is "Re-roll failed charge rolls and hit rolls of 1 for ...." but this has been split into a charge rule and a combat rule - looks like the "of 1" was mistakenly retained in the charge rule.
I haven't modified or run any tests because I don't believe this level of change affects any of them (and I don't yet have yarn installed...).

Fix small typo in rules for Horticulus Slimux's Beast Handler ability

---

src/army/nurgle/units.ts

Another small typo : Nurgle icon bearers (for both plaguebearers and plague drones) have battleshock rules that talk about models "feeling" rather than "fleeing".

Fix small typo in Nurgle icon bearers' battleshock rules

---

src/army/generic/endless_spells.ts

Only the regular versions have these abilities: the bound ones do not.
Fixes #953

Move empowerment off shared endless spell effects

---

src/army/slaves_to_darkness/units.ts
src/army/tzeentch/units.ts

Fixes #840  
Wording was different for Infernal Flames on the gaunt summoner on
foot and the gaunt summoner on disc, so they weren't de-duping
properly.
It's not ideal. These two spells have the same wording now but live in
different factions on here and we don't quite have a standardised style
guide for the wording rewrites we do (eg "Casting value 7" vs "Casting
value of 7" vs "Casting value of 7+" etc) so it's a bit of a judgement
call

Fix weird duplicated Infernal Flames

---

src/army/gloomspite/units.ts

Fixes #930 
They vary on the attack name and whether they do 1 MW or D3 MW
For any instance that refers to a type of Fangs (eg Monstrous Fangs),
these have all been written just as Fangs to allow for deduplication.
One of the warscrolls has the venom on both the spider's fangs and the
rider's weapon, though, so that wording had to stay different

Make all the Spider Venom rules correct

---

src/components/info/reminders.tsx
src/utils/reorder.ts

Fixes #956 
Given that this works, I think it might be the right solution 😁 
There's still some inconsistency when reordering in Play mode, but I think we're agreed on removing that case anyway so I didn't worry about making it work. I did take a quick look at removing it myself but I wasn't sure how to do the conditional stuff I needed around the `Draggable` object.

Make reordering and hiding play nicely together

---

package.json
yarn.lock

This visual bug has presumably been around on mobile since #939 was merged
I'm sure there'll be a way to fix it with the newer version of bootstrap, but reverting is straightforward in the meantime.
Before reverting:
After reverting:

Revert bootstrap upgrade to fix mobile display bug

---

src/components/info/confirm_dismiss_notification_modal.tsx
src/components/input/savedArmies/delete_army_modal.tsx

- In Play Mode in light theme, the "Never Mind" button on the modal for hiding rules was white text and a white outline; now uses the theme 
- In both themes on mobile, the focus outline of the modals was visible as a strange shape distinct from the modal border, because the contents invisibly extended outside the modal. I've fixed this with a quick `flex-row` but there may be better approaches. The contents aren't properly centred within the modal, but that doesn't bother me as much as the outline 😁

Fix a couple of visual bugs on modals

---

src/army/generic/endless_spells.ts

Bound Balewind has its own Summoning rule, so the summoning rule can't
be in the shared ones. I'm a bit uncomfortable it not being in the const
called BalewindVortexEffects, but not quite to the point where I wanted
an interim const without it and that one with it.
Fixes #968

Move summoning rule off core Balewind effects

---

src/components/info/reminder.tsx

I mentioned in chat that I might go to vertical ellipsis for this, but horizontal looked better to me in the end (I think if the icon were vertical aligned to the whole reminder it might have made sense, but with it just part of the title the horizontal one still looked right)

Move reminder dropdown back onto title row on mobile

---

src/components/input/select.tsx
src/factions/daughters_of_khaine/units.ts
src/tests/azyr/getAzyrArmy.test.ts
src/tests/store/units.test.ts

Imports test suggests this already works for imports
Tested in the browser using the dropdowns, and wrote test cases for it
Kudos to the new side effects system for handling removal of members of these pairs, which the old system couldn't do.
Once this is reviewed, I plan to do the Underworlds warbands that have Leader / Unit pairs that you always take together.

Morathi add Morathi

---

src/factions/fyreslayers/units.ts

Magmadroth version was missing Vying for Glory and Wyrmslayer Javelin. It was all set up to be shared by both Auric Runeson warscrolls, just not used.

Add common Auric Runeson effects to mounted one

---

src/factions/idoneth_deepkin/scenery.ts

It's two years old now but we didn't have it right
It's mostly about the timing (after picking sides) but having to keep them apart and off objectives, and what happens if both players have scenery in this window, is also relevant

Update Gloomtide Shipwreck setup rule from FAQ

---

src/factions/kharadron_overlords/command_abilities.ts
src/factions/kharadron_overlords/units.ts
src/factions/ossiarch_bonereapers/scenery.ts

Request for review:
[Output of transport change](https://imgur.com/a/kLufYXe) - would the ironclad addition be better as a tweak more like this instead:
```const FlyingTransportEffect = {
name: `Flying Transport`,
desc: `This model can fly, and can be garrisoned by up to 15 **(25 if Ironclad)** friendly Marine models even though it is not a terrain feature. If this model is in a warscroll battalion, units from the same battalion that can garrison this model can be set up as this model's garrison when this model is set up.
Halve this model's Move characteristic and it cannot Fly High if there are 11 **(16 if Ironclad)** or more models in its garrison. Units cannot join or leave this model's garrison if it has made a move or flown high in the same phase (they can join or leave before it …
```

Fix Ironclad transport rule and add OBR terrain setup

---

src/factions/fyreslayers/units.ts
src/factions/kharadron_overlords/units.ts
src/tests/fixtures/warscroll/json/1589874682978-Warscroll_Builder.json
src/tests/warscroll/warscrollJson.test.ts

I noticed KO had Apprentice Runesmith as a Hero option. Which is incorrect.
When updating this I saw Fyreslayers had him too.
I looked over the code to see why. I could find this PR:  https://github.com/daviseford/aos-reminders/pull/941 with this specific commit https://github.com/daviseford/aos-reminders/pull/941/commits/7a275b322390ee2b41deeafa265811495421b363 that addresses the Runesmith. But couldn't find a reason why this was done.
Looking at the warscroll, it seems his inclusion has been accidental. As the Runesmith isn't allied, and the Skyport isn't Barak Thryng which does allow Duardin units. But they're accessible via the ally function.

Remove Apprentice Runesmith from KO and Fyreslayers

---

src/factions/cities_of_sigmar/prayers.ts
src/factions/cities_of_sigmar/spells.ts
src/factions/cities_of_sigmar/units.ts
src/factions/kharadron_overlords/units.ts
src/factions/sylvaneth/units.ts
src/tests/azyr/getAzyrArmy.test.ts
src/tests/warscroll/warscrollPdf.test.ts

Adds the Cursed City Heroes to their respective lists. 
Some of the rules were quite wordy. Did my best to shorten them.
Also had to adjust some tests to cater for a new spell added to the CoS list.
https://www.games-workshop.com/resources/PDF/AoS_Warscrolls/eng_Brutogg_Corpse_Eater_Dagnai_Holdenstock.pdf
https://www.games-workshop.com/resources/PDF/AoS_Warscrolls/eng_Captain_Emelda_Braskov_Qulathis_The_Exile.pdf
https://www.games-workshop.com/resources/PDF/AoS_Warscrolls/eng_Cleona_Zeitengale.pdf
https://www.games-workshop.com/resources/PDF/AoS_Warscrolls/eng_Glaurio_Ven_Alten_III_Octren_Glimscry.pdf
https://www.games-workshop.com/resources/PDF/AoS_Warscrolls/eng_Jelsen_Darrock.pdf

Adds Cursed City Heroes

---

src/factions/nurgle/command_abilities.ts
src/factions/tzeentch/command_abilities.ts

Added clarification that only mortal units are affected by the ability, not all Nurgle units.
The linter (husky?) also caught a stray space in a Tzeentch file.

Fix: Harbinger of Decay - Morbid Vigour

---

package.json
src/factions/factionClass.ts
src/factions/seraphon/rule_sources.ts
src/factions/soulblight_gravelords/artifacts.ts
src/factions/soulblight_gravelords/spells.ts
src/tests/warscroll/warscrollJson.test.ts
tsconfig.json
yarn.lock

- Added `"useUnknownInCatchVariables": false` to `tsconfig.json` to stop annoying compilation errors (when `catch(err)` was not explicitly defined, we got tons of errors.)

Update Typescript to v4.4.3 (fixes #1408)

---

src/factions/orruk_warclans/ironjawz/command_abilities.ts
src/factions/orruk_warclans/ironjawz/units.ts

Brought to my attention in the AoS subreddit: https://www.reddit.com/r/ageofsigmar/comments/s53nno/comment/htsss5v/?utm_source=share&utm_medium=web2x&context=3
"Go on Ladz, Get Stuck In" was removed from the Megaboss Warscrolls with the new tome.

Orruk Warclans - Remove Command Ability: "Go on Ladz, Get Stuck In"

---

src/factions/orruk_warclans/battle_traits.ts
src/factions/orruk_warclans/big_waaagh/battle_traits.ts
src/factions/orruk_warclans/bonesplitterz/battle_traits.ts
src/factions/orruk_warclans/ironjawz/battle_traits.ts
src/factions/orruk_warclans/kruleboyz/battle_traits.ts
src/factions/orruk_warclans/subfactions.ts
src/tests/processReminders.test.ts

Updated warclans to only show battle tactics when appropriate, though…I could not figure out how to make kragnos trigger his own battle tactic when he was added to the army so it just shows all the time still.

Cleaned up Orruk Warclan Battle Tactics by faction

---

src/factions/sylvaneth/battle_traits.ts
src/factions/sylvaneth/flavors.ts
src/factions/sylvaneth/subfactions.ts

Updated Sylvaneth so it behaves the same as Warclans and Stormcast, where the first subfaction is under the main faction name. Then they can still pick a glade from the list below.

Added Sylvaneth Seasons of War as a subfaction choice

---

src/factions/sylvaneth/units.ts

Sundering Strikes ability triggers on hit roll instead of wound roll

Fix Kurnoth Hunters Sundering Strikes (Greatswords)

---

src/components/page/contact.tsx
src/components/routes/Faq.tsx

Wow that website turned to shit!

Remove Twitter links (deactivated account)

---

src/generic_rules/realmscapes.ts

The Andtor battle tactic Magical Dominance had the rules text for the Intimidate the Invaders tactic

Magical Dominance correction

---

src/factions/orruk_warclans/ironjawz/units.ts
src/factions/orruk_warclans/rule_sources.ts

Updated the Ironjawz units to include the battletome supplement from https://www.warhammer-community.com/wp-content/uploads/2023/09/r8DTAWmkrsW2fiRW.pdf originally released 10/26/2023

Battletome Ironjawz Supplement
